#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 2000 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o log/svm/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e log/svm/%x_%u_%j.err # File to which STDERR will be written
python week3/code/mlp_svm.py
